version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
    ports:
        - "5432:5432"
    volumes:
        - postgresdata:/var/lib/postgresql/data
  
  adminer:
     image: adminer
     ports:
        - "8080:8080"
          
  app:
    image: graph-editor
    restart: always
    build:
      context: .
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Database=graphDb;Username=postgres;Password=postgrespass
    ports:
      - "5021:80"
    depends_on:
      - db
    
volumes:
  postgresdata: