// <auto-generated />
using GraphEditor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraphEditor.Migrations
{
    [DbContext(typeof(GraphDBContext))]
    [Migration("20230407104334_MoveToGraphData")]
    partial class MoveToGraphData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraphEditor.Models.Auth.User.UserRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRecord");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GraphData");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GraphDataId")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GraphDataId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("GraphLink");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GraphDataId")
                        .HasColumnType("text");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("GraphDataId");

                    b.ToTable("GraphNode");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DataId");

                    b.ToTable("GraphRecord");
                });

            modelBuilder.Entity("GraphRecordUserRecord", b =>
                {
                    b.Property<string>("CanEditId")
                        .HasColumnType("text");

                    b.Property<string>("EditorsId")
                        .HasColumnType("text");

                    b.HasKey("CanEditId", "EditorsId");

                    b.HasIndex("EditorsId");

                    b.ToTable("Editors", (string)null);
                });

            modelBuilder.Entity("GraphRecordUserRecord1", b =>
                {
                    b.Property<string>("CanViewId")
                        .HasColumnType("text");

                    b.Property<string>("ViewersId")
                        .HasColumnType("text");

                    b.HasKey("CanViewId", "ViewersId");

                    b.HasIndex("ViewersId");

                    b.ToTable("Viewers", (string)null);
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphLink", b =>
                {
                    b.HasOne("GraphEditor.Models.Graph.GraphData", null)
                        .WithMany("Links")
                        .HasForeignKey("GraphDataId");

                    b.HasOne("GraphEditor.Models.Graph.GraphNode", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("GraphEditor.Models.Graph.GraphNode", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId");

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphNode", b =>
                {
                    b.HasOne("GraphEditor.Models.Graph.GraphData", null)
                        .WithMany("Nodes")
                        .HasForeignKey("GraphDataId");

                    b.OwnsOne("GraphEditor.Models.Graph.GraphNodeMeta", "Meta", b1 =>
                        {
                            b1.Property<string>("GraphNodeId")
                                .HasColumnType("text");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .HasColumnType("text");

                            b1.HasKey("GraphNodeId");

                            b1.ToTable("GraphNode");

                            b1.WithOwner()
                                .HasForeignKey("GraphNodeId");
                        });

                    b.Navigation("Meta")
                        .IsRequired();
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphRecord", b =>
                {
                    b.HasOne("GraphEditor.Models.Auth.User.UserRecord", "Creator")
                        .WithMany("Creations")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphEditor.Models.Graph.GraphData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId");

                    b.Navigation("Creator");

                    b.Navigation("Data");
                });

            modelBuilder.Entity("GraphRecordUserRecord", b =>
                {
                    b.HasOne("GraphEditor.Models.Graph.GraphRecord", null)
                        .WithMany()
                        .HasForeignKey("CanEditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphEditor.Models.Auth.User.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("EditorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphRecordUserRecord1", b =>
                {
                    b.HasOne("GraphEditor.Models.Graph.GraphRecord", null)
                        .WithMany()
                        .HasForeignKey("CanViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphEditor.Models.Auth.User.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("ViewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphEditor.Models.Auth.User.UserRecord", b =>
                {
                    b.Navigation("Creations");
                });

            modelBuilder.Entity("GraphEditor.Models.Graph.GraphData", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
